version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: green_chat_db
      POSTGRES_USER: green_chat_user
      POSTGRES_PASSWORD: securepassword
    networks:
      - green_chat_network

  web:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 green_chat.asgi:application
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles

    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgres://green_chat_user:securepassword@db:5432/green_chat_db
    depends_on:
      - db
    networks:
      - green_chat_network

volumes:
  postgres_data:

networks:
  green_chat_network: